apiVersion: batch/v1
kind: Job
metadata:
  name: spark-wordcount
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: spark
        image: swr.cn-east-3.myhuaweicloud.com/nalacc2405/pyspark:3.4
        imagePullPolicy: Always
        command: ["python", "/opt/spark/work/wordcount.py"]
      restartPolicy: Never
